# Generated by Django 5.0.6 on 2024-07-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_userprofile_follower_userprofile_follwing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Follower',
            new_name='follower',
        ),
    ]
