# Generated by Django 5.0.6 on 2024-07-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_rename_follower_userprofile_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'follower')},
        ),
    ]
