# Generated by Django 5.0.6 on 2024-07-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_follower_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
