# Generated by Django 5.0.6 on 2024-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_profile_pic_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='profile_pics/'),
        ),
    ]
