# Generated by Django 5.0.6 on 2024-07-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_refreshtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='follwing',
            new_name='following',
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='User.userprofile'),
        ),
    ]
