# Generated by Django 5.0.6 on 2024-08-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_refreshtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='is_active',
        ),
    ]
