# Generated by Django 5.0.6 on 2024-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_refreshtoken_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='https://www.w3schools.com/howto/img_avatar.png'),
        ),
    ]
