# Generated by Django 5.0.6 on 2024-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='https://www.w3schools.com/howto/img_avatar.png', upload_to='profile_pics/'),
        ),
    ]
