# Generated by Django 5.0.6 on 2024-08-04 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
